import IProject from 'types/project';

const items: IProject[] = [
  {
    id: 'pedicab',
    name: 'Pedicab',
    description: 'Make urls shorter and more meaningful',
    banner: '/images/projects/banners/pedicab.jpeg',
    screenshots: [
      '/images/projects/screenshots/pedicab/1.jpeg',
      '/images/projects/screenshots/pedicab/2.jpeg',
      '/images/projects/screenshots/pedicab/3.jpeg',
      '/images/projects/screenshots/pedicab/4.jpeg',
    ],
    tags: [
      'url',
      'short',
      'custom',
      'shortener',
      'meaningful',
      'easy to remember',
    ],
    techstacks: [
      'react',
      'nextjs',
      'tailwind',
      'typescript',
      'nodejs',
      'express',
      'mongodb',
    ],
  },
  {
    id: 'recipes',
    name: 'Recipes',
    description: 'Share or find awesome recipes',
    banner: '/images/projects/banners/recipes.jpeg',
    screenshots: [
      '/images/projects/screenshots/recipes/1.jpeg',
      '/images/projects/screenshots/recipes/2.jpeg',
      '/images/projects/screenshots/recipes/3.jpeg',
      '/images/projects/screenshots/recipes/4.jpeg',
      '/images/projects/screenshots/recipes/5.jpeg',
    ],
    tags: [
      'bake',
      'dish',
      'tasty',
      'manual',
      'recipe',
      'cooking',
      'cuisine',
      'delicious',
      'how to cook',
    ],
    techstacks: [
      'react',
      'nextjs',
      'tailwind',
      'typescript',
      'python',
      'fastapi',
      'postgres',
    ],
  },
  {
    id: 'cedar-college',
    name: 'Cedar College',
    description: 'Official website of Cedar College',
    banner: '/images/projects/banners/cedar.jpeg',
    screenshots: [
      '/images/projects/screenshots/cedar/1.jpeg',
      '/images/projects/screenshots/cedar/2.jpeg',
      '/images/projects/screenshots/cedar/3.jpeg',
      '/images/projects/screenshots/cedar/4.jpeg',
      '/images/projects/screenshots/cedar/5.jpeg',
      '/images/projects/screenshots/cedar/6.jpeg',
      '/images/projects/screenshots/cedar/7.jpeg',
      '/images/projects/screenshots/cedar/8.jpeg',
    ],
    tags: [
      '6100',
      'cedar',
      'school',
      'college',
      'cadiz city',
      'official website',
      'senior highschool',
    ],
    techstacks: [
      'react',
      'nextjs',
      'tailwind',
      'typescript',
      'python',
      'fastapi',
      'postgres',
    ],
  },
];

export default items;
